name = "fuzzy-vid-worker"
main = "worker/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "STORY_STORAGE"
bucket_name = "igome-story-storage"

[[kv_namespaces]]
binding = "JOB_STATUS"
id = "fc732a268ca9435b8de8e50f34a35365"
preview_id = "fc732a268ca9435b8de8e50f34a35365"

[vars]
ENVIRONMENT = "production"

workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "fuzzy-short-db"
database_id = "690a4a7f-5885-4261-921b-2dba40dec104"
migrations_dir = "worker/migrations"

[ai]
binding = "AI"

[assets]
binding = "ASSETS"
not_found_handling = "single-page-application"

